[package]
name = "tree"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "*"
trees = "0.4.2"
binartree = "2.0.2"
ptree = "0.3.2"
binary-tree="0.2.0"
libmath="0.2.1"
rand="0.8.0"
